### ISSUE TITLE
Wow this is an awesome demo of what you can do but cannot get it to run

### ISSUE THREAD

**Issue by richtong** [hamsterbacke23/webcamdisplay-react#1]
Thanks for doing this demonstration code, it is an awesome thing that I really need to learn. I just forked the repo and am trying to get it to run on my Mac. I installed yarn and tried 'yarn installl npm start' but it looks like they've change this to 'yarn add npm start' however when I run this new command, I get an error when I try to run 'yarn' by itself...

```
WARNING in ./~/npm/lib/npm.js
117:16 Critical dependency: the request of a dependency is an expression

WARNING in ./~/npm/lib/npm.js
224:10 Critical dependency: the request of a dependency is an expression

ERROR in ./~/npm/lib/npm.js
Module not found: Error: Can't resolve 'fs' in '/Users/rich/ws/git/webcamdisplay-react/node_modules/npm/lib'
 @ ./~/npm/lib/npm.js 21:27-40
 @ dll reactBoilerplateDeps
```

I'm wondering if something changed in yarn that makes it hard to build this, in looking at. I'm using yarn 1.2.1, node 8.7 and npm 5.4

As an aside if I try just to use npm start by itself

**Comment by LukasOchmann** [comment]
First install all dependencies by run:
yarn install
Then start the app by running:
npm start

**Comment by richtong** [comment]
When I try to run yarn install. It says yarn install is deprecated. Use yarn add. This then fails. I’ll run again and send errors. Sorry to be such a noob I haven’t used yarn before. Your non react version works great. Just needs npm install. 

Thanks,
Rich

No! Try not. Do, or do not. There is no try. Master Yoda. Star Wars Episode V: The Empire Strikes Back

http://tongfamily.com | @richtong | http://fb.me/richtong1 | +1-206-963-9029

**Comment by hamsterbacke23** [comment]
Sounds like this  [react-boilerplate issue](https://github.com/react-boilerplate/react-boilerplate/issues/1278) ?

**Comment by richtong** [comment]
Don’t you love it when the scaffolding itself breaks. Ok looking at this now.


Thanks
Rich

—
Can you pull the train over the hill? I think I can, I think I can, I think I can, I think... I can… I thought I could, I thought I could! Story of the Engine that Cloud (1902, Author unknown)
---
http://tongfamily.com | https://github.com/richtong | https://linkedin.com/in/richtong1 | https://fb.me/richtong1 | @richtong | +1-206-963-9029

**Comment by richtong** [comment]
OK I think I see the issue, I misread the README.md, you should first to a `yarn install` and then a `npm start` so I get a different error. I sent you a PR on this.
