### ISSUE TITLE
yarn setup from Lukas branch fails when yarn setup incomplete

### ISSUE THREAD

**Issue by richtong** [hamsterbacke23/webcamdisplay-react#5]
OK, I can get this running by disabling ssl on my own branch, but when I try to run Lukas's fix, I have a problem during 'yarn setup' it seems to do the ssl setup ok, but  at `npm run build:dll' the error:

```
Enter Export Password:
Verifying - Enter Export Password:
$ npm run build:dll

> react-boilerplate@3.4.0 build:dll /Users/rich/ws/git/webcamdisplay-react
> node ./internals/scripts/dependencies.js

module.js:529
    throw err;
    ^

Error: Cannot find module 'lodash/defaultsDeep'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/rich/ws/git/webcamdisplay-react/internals/scripts/dependencies.js:13:18)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-boilerplate@3.4.0 build:dll: `node ./internals/scripts/dependencies.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-boilerplate@3.4.0 build:dll script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rich/.npm/_logs/2017-10-23T04_13_39_646Z-debug.log
error Command failed with exit code 1.
```

**Comment by richtong** [comment]
The only thing I could find from google was a note that yarn install may have failed, I tried, but this still results in the same error

```
rm -rf node_modules
```

And then run yarn install again. See https://github.com/react-boilerplate/react-boilerplate/issues/1500

My branch which disables ssl seems to be ok, so Lukas are you having th same issues, how is your configuration. different. I don't really understand what web pack and react boilerplate are doing under the covers, but your sslsetup.sh was very helpful.

**Comment by richtong** [comment]
yes this is the problem, by the way with the way the script is currently run there appears to be no way that httpsenabled can be set to false

**Comment by richtong** [comment]
I'll issue a new PR so that the documentation changes to note that if you get a lodash or other module not found, to use `rm node_modules` also apparently you need a last npm for this to work according to the folks at react-boilerplate. It does not run with npm@2

**Comment by hamsterbacke23** [comment]
I got this error as well that's why I didn't merge anything yet..
Therefore I think this is an issue with #4 and should be discussed there

**Comment by richtong** [comment]
The Current branch either need to say. Certificate files for certificates or move the open of certificates after the check for httpsenabled. Either work.
